version: "3"
services:
    frontend:
        build: ui/
        restart: always
        volumes:
            - data-gen:/var/www/html/ui/data-gen
        networks:
            - default
        depends_on:
            - backend
    backend:
        build: generator2/org.getaviz.generator/
        restart: always
        volumes: 
            - data-gen:/var/lib/jetty/data-gen
        networks:
            - default
        depends_on:
            - jqassistant
    tests:
        build: integrationtests/
        command: "mvn clean install"
        networks:
            - default
        depends_on:
            - jqassistant
            - frontend
            - backend
    jqassistant:
        build: jQAssistant/
        restart: always
        volumes:
            - 'getaviz-db:/data'
        ports:
            - "7474:7474"
            - "7687:7687"
            - "8080:8080"
        environment:
            NEO4J_AUTH: "none"
        networks:
            - default
    volumes-provisioner:
        image: hasnat/volumes-provisioner
        environment:
            PROVISION_DIRECTORIES: "100:101:0755:/var/data /var/data/data-gen/"
        volumes:
           - data-gen:/var/data
volumes:
    data-gen:
    getaviz-db:
    
networks:
    default:
        driver: bridge
