version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dbpassword_for_user
      MYSQL_DATABASE: eval_server_development
      MYSQL_USER: db_username
      MYSQL_PASSWORD: dbpassword_for_user
    restart: always
  eval:
    build: evaluationserver
    restart: always
    env_file: evaluationserver/env
    command: "./bin/wait-for-it.sh db:3306 -s -t 30 -- ./bin/docker_start"
    #volumes:
      #- ./evaluationserver:/usr/src/app
    ports:
      - "8081:8081" 
    depends_on:
      - db
  frontend:
    build: ui/
    restart: always
    volumes:
      #- ./ui:/var/www/html/ui # uncomment only for ui development
      - data-gen:/var/www/html/ui/data-gen
    ports:
      - "8082:80"
    networks:
      - default
    depends_on:
      - backend
  backend:
    build: generator2/org.getaviz.generator/
    restart: always
    volumes: 
      - data-gen:/var/lib/jetty/data-gen
      - ./input:/var/lib/jetty/input
     #- ./generator2/org.getaviz.generator/target/org.getaviz.generator-1.0.0-SNAPSHOT.war:/var/lib/jetty/webapps/root.war # uncomment only for generator development
    ports:
      - "8083:8080"
    networks:
      - default
    depends_on:
      - jqassistant
      - volumes-provisioner
  jqassistant:
    build: jQAssistant/
    restart: always
    volumes:
      - 'getaviz-db:/data'
     # - ./jQAssistant/target/org.getaviz.jqassistant-1.0.0-SNAPSHOT.war:/getaviz-jqassistant.war # uncomment only for development
    ports:
      - "7474:7474"
      - "7687:7687"
      - "8080:8080"
    environment:
      NEO4J_AUTH: "none"
    networks:
      - default
  volumes-provisioner:
    image: hasnat/volumes-provisioner
    environment:
      PROVISION_DIRECTORIES: "100:101:0755:/var/data /var/data/data-gen/"
    volumes:
      - data-gen:/var/data
volumes:
  data-gen:
  getaviz-db:
    
networks:
  default:
    driver: bridge
